# Traefik static configuration file
# This file contains the base configuration for Traefik
# If you update this, you need to restart the Traefik pod for the changes to take effect

# API and Dashboard configuration
api:
  dashboard: false
  insecure: true

# Entrypoints configuration
entryPoints:
  web:
    address: ":80"
    

# Providers configuration
providers:
  # File provider for dynamic configuration
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Logging configuration
log:
  level: INFO
  format: json

# Access log configuration
# Access logs are written to stdout by default
accessLog:
  format: json

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

